In [1]:
import pandas as pd

pd.read_csv("cartpole_log.csv")

       timestamp         x      xdot     theta  thetadot    action
0   1.665338e+09  0.000000 -0.002543  0.107291  0.056264  2.201331
1   1.665338e+09 -0.000085  0.066443  0.109167  0.005853  2.209082
2   1.665338e+09  0.002130  0.135634  0.109362 -0.043931  2.185065
3   1.665338e+09  0.006651  0.204041  0.107898 -0.092447  2.130044
4   1.665338e+09  0.013453  0.270696  0.104816 -0.139082  2.045176
..           ...       ...       ...       ...       ...       ...
95  1.665338e+09  0.062673 -0.458479 -0.011849  0.221547 -0.121630
96  1.665338e+09  0.047391 -0.462152 -0.004464  0.221251  0.017028
97  1.665338e+09  0.031985 -0.461492  0.002911  0.218074  0.153847
98  1.665338e+09  0.016602 -0.456558  0.010181  0.212100  0.287044
99  1.665338e+09  0.001384 -0.447466  0.017251  0.203451  0.414913

[100 rows x 6 columns]